// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpgvkfnozbkdfbyfefac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwZ3ZrZm5vemJrZGZieWZlZmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjkyMDEsImV4cCI6MjA2NDM0NTIwMX0.iXPkk8ahdO8VxlgA5h1VM3iXzjbNAa83kCpI0-H5y5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);